//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dow.Template.AngularApp.Data.Interface
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SecurityRole()
        {
            this.SecurityUserRoles = new HashSet<SecurityUserRole>();
        }
    
        public int SecurityRoleId { get; set; }
        public string SecurityRoleName { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecurityUserRole> SecurityUserRoles { get; set; }
    }
}
